version: 2
jobs:
  build:
    docker:
      - image: lucazader/fedora_gcc_embedded
    working_directory: ~/anova_stm32
    steps:
      - run: arm-none-eabi-gcc --version
      - checkout
      - run: mkdir release
      - run:
          name: cmake configure - release
          command: cd release &&
              cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/arm_gcc_toolchain.cmake
              -G Ninja -DCMAKE_BUILD_TYPE=Release ../ &&
              ninja

      - run: mkdir debug
      - run:
          name: cmake configure - debug
          command: cd debug &&
              cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/arm_gcc_toolchain.cmake 
              -G Ninja -DCMAKE_BUILD_TYPE=Debug ../ &&
              ninja
